-- MySQL Script generated by MySQL Workbench
-- Вск 21 июн 2020 15:28:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema practice_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema practice_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practice_DB` DEFAULT CHARACTER SET utf8 ;
USE `practice_DB` ;

-- -----------------------------------------------------
-- Table `practice_DB`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practice_DB`.`Authors` (
  `author_id` INT(11) NOT NULL AUTO_INCREMENT,
  `f_name` VARCHAR(45) NOT NULL,
  `l_name` VARCHAR(45) NOT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `author_pay` INT(11) NULL DEFAULT NULL,
  `card_code` VARCHAR(45) NOT NULL,
  `passport_code` VARCHAR(45) NOT NULL,
  `inn_code` INT(11) NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `practice_DB`.`Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practice_DB`.`Types` (
  `type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `practice_DB`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practice_DB`.`Books` (
  `book_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `price` INT(11) NOT NULL,
  `circulation` INT(11) NOT NULL,
  `advance` INT(11) NOT NULL,
  `public_date` DATE NOT NULL,
  `type_id` INT(11) NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_Books_Types1_idx1` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Books_Types1`
    FOREIGN KEY (`type_id`)
    REFERENCES `practice_DB`.`Types` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `practice_DB`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practice_DB`.`Customers` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `f_name` VARCHAR(45) NOT NULL,
  `l_name` VARCHAR(45) NOT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `practice_DB`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practice_DB`.`Items` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `author_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_Titles_Authors_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_Titles_Books1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_Titles_1`
    FOREIGN KEY (`author_id`)
    REFERENCES `practice_DB`.`Authors` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Titles_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `practice_DB`.`Books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `practice_DB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practice_DB`.`Orders` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `book_id` INT(11) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_Orders_3_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_Orders_1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `practice_DB`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `practice_DB`.`Books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
